name: Build TokenPay

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          # Navigate to the depends directory
          cd depends
          # Run your build scripts to compile dependencies, if any
          make all

      - name: Build the project
        run: |
          # Navigate to the root of your project
          cd ..
          # Set any necessary environment variables
          export PATH="$PATH:$(pwd)/depends/x86_64-linux-gnu/bin"
          export LD_LIBRARY_PATH="$(pwd)/depends/x86_64-linux-gnu/lib:$LD_LIBRARY_PATH"
          
          # Run the build commands, assuming you have a Makefile or similar setup
          make -C depends/x86_64-linux-gnu

      - name: Run tests
        run: |
          # Assuming you have tests to run after building
          make test
